config/routes.rb
WeddingCourier::Application.routes.draw do
  resources :weddings

  devise_for :couples

  root :to => 'home#index'

  get "home/index"

end

app/models/couple.rb
class Couple < ActiveRecord::Base
  has_one :wedding

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
  belongs_to :couple

  attr_accessible :bride_name, :couple_id, :groom_name, :story, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  # GET /weddings
  # GET /weddings.json
  def index
    @weddings = Wedding.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weddings }
    end
  end

  # GET /weddings/1
  # GET /weddings/1.json
  def show
    @wedding = Wedding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wedding }
    end
  end

  # GET /weddings/new
  # GET /weddings/new.json
  def new
    @wedding = Wedding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wedding }
    end
  end

  # GET /weddings/1/edit
  def edit
    @wedding = Wedding.find(params[:id])
  end

  # POST /weddings
  # POST /weddings.json
  def create
    @wedding = Wedding.new(params[:wedding])

    respond_to do |format|
      if @wedding.save
        format.html { redirect_to @wedding, notice: 'Wedding was successfully created.' }
        format.json { render json: @wedding, status: :created, location: @wedding }
      else
        format.html { render action: "new" }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weddings/1
  # PUT /weddings/1.json
  def update
    @wedding = Wedding.find(params[:id])

    respond_to do |format|
      if @wedding.update_attributes(params[:wedding])
        format.html { redirect_to @wedding, notice: 'Wedding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weddings/1
  # DELETE /weddings/1.json
  def destroy
    @wedding = Wedding.find(params[:id])
    @wedding.destroy

    respond_to do |format|
      format.html { redirect_to weddings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/home/index.html.erb
<h1>WeddingCourierへようこそ !</h1>

<div class="welcome">
  <div class="row">    
    <div class="span6">
      <p class="announce">
        <br /><br /><br />
        Create a beautiful website for your wedding,<br />
        that you can show your guests! <br /> <br /><br />
        
        <span style="font-size: 22px;">
          結婚式にそなえて素敵なウェブサイトを作りましょう!
        </span>
        <br />
      </p>
      <p class="hint">
        Want to send invitations for your wedding? <a href="/">Click here</a>
      </p>
    </div>
    <div class="span6">
      <%= image_tag('happycouple.png') %>
    </div>
  </div>
  <div class="span12">
    <p class="start-button">
      <a class="btn btn-primary btn-large" href="<%= new_couple_registration_path %>">
        Create your website!
      </a>      
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WeddingCourier" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">

    <!-- Adding Google Web Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">WeddingCourier</a>
        </div>
      </div>
    </div>

    <!-- Main -->
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      <div class="content">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/weddings/_form.html.erb
<%= simple_form_for(@wedding) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :couple_id %>
    <%= f.input :title %>
    <%= f.input :story %>
    <%= f.input :groom_name %>
    <%= f.input :bride_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/weddings/edit.html.erb
<h1>Editing wedding</h1>

<%= render 'form' %>

<%= link_to 'Show', @wedding %> |
<%= link_to 'Back', weddings_path %>

app/views/weddings/index.html.erb
<h1>Listing weddings</h1>

<table>
  <tr>
    <th>Couple</th>
    <th>Title</th>
    <th>Story</th>
    <th>Groom name</th>
    <th>Bride name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weddings.each do |wedding| %>
  <tr>
    <td><%= wedding.couple_id %></td>
    <td><%= wedding.title %></td>
    <td><%= wedding.story %></td>
    <td><%= wedding.groom_name %></td>
    <td><%= wedding.bride_name %></td>
    <td><%= link_to 'Show', wedding %></td>
    <td><%= link_to 'Edit', edit_wedding_path(wedding) %></td>
    <td><%= link_to 'Destroy', wedding, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wedding', new_wedding_path %>

app/views/weddings/new.html.erb
<h1>New wedding</h1>

<%= render 'form' %>

<%= link_to 'Back', weddings_path %>

app/views/weddings/show.html.erb
<% content_for :title do %>
  <%= @wedding.title %>Z
<% end %>

<p id="notice"><%= notice %></p>

<div class="span12">
  <h1 style="text-align:center">
    <%= @wedding.title %>
  </h1>
</div>
<br />

<div class="row">
  <div class="span6 withBackground couple" style="text-align:left">
    <p style="text-align:left">
      <h2>The Bride: <%= @wedding.bride_name %></h2>
      <%= image_tag 'eri.png' %>
    </p>
  </div>
  <div class="span6 withBackground couple" style="text-align:right">
    <p style="text-align:right">
      <h2>The Groom: <%= @wedding.groom_name %></h2>
      <%= image_tag 'joshua.png' %>
    </p>
  </div>
</div>

<div class="withBackground">
  <h2>Our story</h2>
  <%= @wedding.story %>
  <p class="story">
    Put a bird on it wayfarers locavore, DIY cosby sweater twee organic. Et odio occaecat laborum. Polaroid scenester wes anderson DIY, thundercats marfa pariatur forage photo booth. Aliquip nisi lomo do velit, gluten-free pop-up iphone. Deserunt cliche ullamco odio kale chips keytar, skateboard aute farm-to-table cosby sweater wolf. Single-origin coffee put a bird on it scenester bicycle rights authentic. Laborum PBR marfa food truck cred aliquip, adipisicing direct trade velit put a bird on it seitan gentrify farm-to-table 8-bit.

    Seitan portland eiusmod narwhal. Before they sold out organic sriracha tumblr chambray aliqua fanny pack, minim 8-bit vero. Cred godard next level, thundercats ullamco nisi kale chips. Brunch fanny pack sartorial, echo park eu fap aesthetic. Freegan pitchfork incididunt, assumenda typewriter keytar commodo put a bird on it fixie tofu cliche veniam chillwave aesthetic esse. Ethnic lomo delectus esse cliche. Gastropub brooklyn nostrud before they sold out iphone four loko elit, selvage adipisicing eiusmod.
  </p>
</div>

<%= link_to 'Edit', edit_wedding_path(@wedding) %> |
<%= link_to 'Back', weddings_path %>